name: Publish a release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1.4.3
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1.4.3
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1.4.3
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@contasystemer'
      - run: echo "::set-env name=NODE_AUTH_TOKEN::${{secrets.PUBLISH_GITHUB_TOKEN}}"
      - run: npm ci
      - run: echo registry=https://npm.pkg.github.com/contasystemer >> .npmrc
      - run: npm publish