name: Run tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1.4.3
      - run: npm ci
      - run: npm test
